/**
 * A structure generated by a single element.
 *
 * Every element can be obtained by repeatedly applying the operation
 * to the generator.
 *
 * @template TElement - The element type.
 */
interface Cyclic<TElement> {
  generator: TElement;
}

export type {
  Cyclic
};
