import type {Group} from '../group';
import type {Commutative, Cyclic} from '../properties';

/** A group generated by a single element. Every cyclic group is abelian. */
type CyclicGroup<TElement> = (Group<TElement> & Cyclic<TElement> & Commutative);

export type {
  CyclicGroup
};
