import type {Finite} from '../properties';
import type {CyclicGroup} from './cyclic-group';

/** A finite group generated by a single element. */
type FiniteCyclicGroup<TElement> = (CyclicGroup<TElement> & Finite<TElement>);

export type {
  FiniteCyclicGroup
};
